version: '3'
services:
    nextcloud:
        image: nextcloud
        container_name: nextcloud
        depends_on:
        - redis
        links:
        - db
        environment:
        - UID=1000
        - GID=1000
        - UPLOAD_MAX_SIZE=10G
        - APC_SHM_SIZE=128M
        - OPCACHE_MEM_SIZE=128
        - CRON_PERIOD=15m
        - TZ=Aisa/Shanghai
        - DOMAIN=${DOMAIN}
        - DB_TYPE=${TYPE}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWOR=${DB_PASSWORD}
        - DB_HOST=db:3306
        volumes:
        - /docker/nextcloud:/var/www/html
        expose:
        - 8888
        ports:
        - 8888:80/tcp
        
    redis:
        image: redis:alpine
        container_name: redis
        expose:
        - 6379
        
    onlyoffice:
        image: onlyoffice/documentserver
        container_name: onlyoffice
        hostname: onlyoffice
        environment:
        - REDIS_SERVER_HOST=redis
        - REDIS_SERVER_PORT=6379
        volumes:
        - /docker/onlyoffice/data:/var/www/onlyoffice/Data
        - /docker/onlyoffice/logs:/var/log/onlyoffice
        expose:
        - 9000
        - 9001
        ports:
        - 9000:80
        - 9001:443
        links:
        - db
        
        
    db:
        image: mysql:5.7.28
        container_name: db
        ports:
        - 3306:3306
        environment:
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
        - MYSQL_USER=${USER}
        - MYSQL_PASSWORD=${PASSWORD}
